### ISSUE TITLE
Show zone boundaries

### ISSUE THREAD

**Issue by ManDude** [cbhacks/CrashEdit#87]
Something like this:
![screenshot_4](https://cloud.githubusercontent.com/assets/7569514/11609156/cb848608-9b76-11e5-932e-f8a0ccfcbf58.png)

(It should only this for the zone you're currently in.)

Useful (and probably necessary?) for seeing collision.

**Comment by ughman** [comment]
Damn, that looks good too.

**Comment by AraHaan** [comment]
It would be nice to have a version of the 3d viewer where you can optionally see all the zones put together to know what the level as a whole looks like to determine which zone goes where and that you can go right to the zone you want by double clicking on it or something.
Also why does some parts of the Crash Bandicoot 3 Warp room (G Nin's area to be exact) looks like it is moved towards and past Tiny's area. Is this a visual bug?
![19d61a795b90724db8dd2fe4042b7000](https://cloud.githubusercontent.com/assets/15173749/14772853/606dd1ec-0a68-11e6-9ab0-95b19f306496.png)

**Comment by ManDude** [comment]
That version of CrashEdit does not support Crash 3 scenery (vertex positions are unsigned in Crash 3, unlike Crash 1 and 2).

**Comment by AraHaan** [comment]
And it is the latest I have in the Newgui branch too. So this means you need to add Crash Bandicoot 3 Scenery support when they select Crash 3.

**Comment by ManDude** [comment]
[Use my fork](https://github.com/ManDude/CrashEdit) for a while until the features are added.

**Comment by AraHaan** [comment]
ah so you have Crash 3 cenery support I like.

**Comment by AraHaan** [comment]
Ok so I compiled your branch and everything fine but now I get this when I try the 3D viewer. @ManDude

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Top-level control cannot be added to a control.
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at CrashEdit.UndockableControl..ctor(Control control) in E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\Controls\UndockableControl.cs:line 19
   at CrashEdit.ZoneEntryController.CreateEditor() in E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\Controllers\Zone\ZoneEntryController.cs:line 43
   at CrashEdit.Controller.get_Editor() in E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\Controllers\Controller.cs:line 99
   at CrashEdit.NSFBox.trvMain_AfterSelect(Object sender, TreeViewEventArgs e) in E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\Controls\NSFBox.cs:line 115
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///E:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
CrashEdit
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Users/Elsword/Desktop/CrashEdit-newgui/CrashEdit/bin/Release/CrashEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
    CodeBase: file:///E:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///E:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
    CodeBase: file:///E:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Crash
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Users/Elsword/Desktop/CrashEdit-newgui/CrashEdit/bin/Release/Crash.DLL
----------------------------------------
Crash.UI
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Users/Elsword/Desktop/CrashEdit-newgui/CrashEdit/bin/Release/Crash.UI.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.2225.0
    CodeBase: file:///E:/Users/Elsword/Desktop/CrashEdit-newgui/CrashEdit/bin/Release/OpenTK.GLControl.DLL
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.2225.0
    CodeBase: file:///E:/Users/Elsword/Desktop/CrashEdit-newgui/CrashEdit/bin/Release/OpenTK.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by ManDude** [comment]
Did you change ANYTHING? I never got that.

**Comment by AraHaan** [comment]
No, I did not.
Also it seems that on your repo that the entries are not scaled right also some of the entries look like paths so I refer to them as paths those are not scaled right either they look too big.

**Comment by ManDude** [comment]
Yes I know. Scaling in Crash 3 is still an issue. That game sucks.
